[package]
name = "nees"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4.3"
rand = "0.8.5"
rand_distr = "0.4.3"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = {version = "1.0.133" }
